name: build
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: sudo apt-get install -y libgtest-dev
    - name: make
      run: make
    - name: make test
      run: make test
    - name: coverage report
      uses: codecov/codecov-action@v1.5.0
      with:
        file: bld/html.hpp.gcov
